// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useRef, useState } from "react";
import "./CartDrawer.css";
import { FaTimes } from "react-icons/fa";
import { FaChevronLeft, FaChevronRight } from "react-icons/fa";
import { useCart } from "./CartContext.jsx";
import { Link} from "react-router-dom";

const CartDrawer = () => {
  const { cartOpen, closeCart, cartItems, increaseQty, decreaseQty, removeFromCart, addToCart } = useCart();
  const recRef = useRef(null);
  const [recOpen, setRecOpen] = useState(true);

  return (
    <>
      {/* Backdrop overlay */}
      <div
        className={`cart-backdrop ${cartOpen ? "visible" : ""}`}
        onClick={closeCart}
        aria-hidden={!cartOpen}
      />

      <div className={`cart-drawer ${cartOpen ? "open" : ""}`}>
        <div className="cart-header">
          <div className="cart-header-left">
            <span className="cart-title">CART ({cartItems.length})</span>
            <span className="cart-promo">Spend $30 more to save $30!</span>
          </div>
          <button className="cart-close-btn" onClick={closeCart} aria-label="Close cart">
            <FaTimes size={22} />
          </button>
        </div>
      <div className="cart-body">
        {cartItems.length === 0 ? (
          <div className="cart-empty">Your cart is empty.</div>
        ) : (
          cartItems.map((item) => (
            <div className="cart-item" key={item.id}>
              <img src={item.image} alt={item.name} />
              <div className="cart-item-details">
                <div className="cart-item-name">{item.name}</div>
                <div className="cart-item-info">
                  <span>Color: {item.color}</span>
                  <span>Size: {item.size}</span>
                </div>
                <div className="cart-item-actions">
                  <button onClick={() => decreaseQty(item.id)} aria-label={`Decrease quantity of ${item.name}`}>-</button>
                  <span>{item.quantity}</span>
                  <button onClick={() => increaseQty(item.id)} aria-label={`Increase quantity of ${item.name}`}>+</button>
                </div>
              </div>
              <div className="cart-item-right">
                <div className="cart-item-price">${item.price}</div>
                <button className="cart-remove-btn" onClick={() => removeFromCart(item.id)} aria-label={`Remove ${item.name}`}><FaTimes /></button>
              </div>
            </div>
          ))
        )}
      </div>
      {/* Recommended carousel */}
      <div className="recommended-section">
        <div className="rec-header">
          <span>RECOMMENDED FOR YOU</span>
          <button
            className={`rec-collapse-btn ${recOpen ? 'open' : 'collapsed'}`}
            aria-label={recOpen ? 'collapse recommended' : 'expand recommended'}
            onClick={() => setRecOpen(v => !v)}
          >
            <span className="chev">▾</span>
          </button>
        </div>
        <div className={`rec-carousel-wrapper ${recOpen ? 'expanded' : 'collapsed'}`}>
          <div className="rec-carousel" ref={recRef} style={{ display: recOpen ? 'flex' : 'none' }}>
            {/* sample recommended items */}
            {[
              { id: 'r1', title: 'Anytime No Show Sock', img: './images/Products/A11631_25Q3_Wool-Cruiser-Dark-Camel-Natural-White-Sole_PDP_LEFT__1_bec494cd-90bc-4d1a-b180-cd8a56464781.png', price: 9, listPrice: 14 },
              { id: 'r2', title: 'Low Cut Sock', img: './images/Products/A11893_25Q3_Tree-Glider-Thunder-Green-Stony-Cream-Sole_PDP_LEFT__1.png', price: 9, listPrice: 14 },
              { id: 'r3', title: 'Everyday Sock', img: './images/Products/A11837_25Q3_Wool-Cruiser-NZ-Light-Blue-Natural-White-Sole_PDP_LEFT__1_1.png', price: 9, listPrice: 14 }
            ].map(product => (
              <div className="rec-card" key={product.id}>
                <img src={product.img} alt={product.title} />
                <div className="rec-card-body">
                  <div className="rec-title">{product.title}</div>
                  <div className="rec-dots">
                    <span className="dot" style={{background:'#fff'}}></span>
                    <span className="dot" style={{background:'#000'}}></span>
                    <span className="dot" style={{background:'#9b9b9b'}}></span>
                    <span className="dot" style={{background:'#d6cfc6'}}></span>
                  </div>
                  <div className="rec-price"><span className="sale">${product.price}</span> <span className="list">${product.listPrice}</span></div>
                  <div className="rec-controls">
                    <select className="rec-size">
                      <option>Size: S (W5-7)</option>
                      <option>Size: M (W8-9)</option>
                    </select>
                    <button
                      className="rec-add"
                      onClick={() => {
                        const newItem = {
                          id: `rec-${product.id}-${Date.now()}`,
                          image: product.img,
                          name: product.title,
                          color: 'Default',
                          size: 'S',
                          price: product.price,
                          quantity: 1
                        };
                        addToCart(newItem);
                      }}
                    >Add+</button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
      <div className="cart-footer">
        <div className="cart-subtotal">
          <span>Subtotal</span>
          <span>
            ${cartItems.reduce((sum, item) => sum + item.price * item.quantity, 0)}
          </span>
        </div>
        <Link to="/checkout"><button className="cart-checkout-btn">CHECKOUT</button></Link>
        <div className="cart-express-btns">
          <button className="amazon-pay">amazon pay</button>
          <button className="paypal">PayPal</button>
          <button className="shop-pay">shop Pay</button>
        </div>
      </div>
      </div>
    </>
  );
};

export default CartDrawer;
