// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from "react";
import './CategoryHomepage.css'

function CategoryBoxBestseller() {
  const [isHover, setIsHover] = useState(false);

  return (
    <div
      className="category-box"
      onMouseEnter={() => setIsHover(true)}
      onMouseLeave={() => setIsHover(false)}
    >
      <img src="./images/homepage/category-bestseller.png" alt="" />
      <div className="button-box" style={{ bottom: isHover ? "250px" : "200px" }}>
        <button style={{ border: isHover ? "none" : "1px solid white",background:'none' }}>Bestseller</button>
        <button className="button-invisible" style={{ display: isHover ? "block" : "none" }}>
          Shop Men
        </button>
        <button className="button-invisible" style={{ display: isHover ? "block" : "none" }}>
          Shop Women
        </button>
      </div>
    </div>
  );
}

function CategoryBoxMen() {
  const [isHover, setIsHover] = useState(false);

  return (
    <div
      className="category-box"
      onMouseEnter={() => setIsHover(true)}
      onMouseLeave={() => setIsHover(false)}
    >
      <img src="./images/homepage/category-men.png" alt="" />
      <div className="button-box" style={{ bottom: isHover ? "250px" : "200px" }}>
        <button style={{ border: isHover ? "none" : "1px solid white" ,background:'none' }}>Mens</button>
        <button className="button-invisible" style={{ display: isHover ? "block" : "none" }}>
          Shop Men
        </button>
      </div>
    </div>
  );
}

function CategoryBoxWomen() {
  const [isHover, setIsHover] = useState(false);

  return (
    <div
      className="category-box"
      onMouseEnter={() => setIsHover(true)}
      onMouseLeave={() => setIsHover(false)}
    >
      <img src="./images/homepage/category-women.png" alt="" />
      <div className="button-box" style={{ bottom: isHover ? "250px" : "200px" }}>
        <button style={{ border: isHover ? "none" : "1px solid white" ,background:'none'}}>Womens</button>
        <button className="button-invisible" style={{ display: isHover ? "block" : "none" }}>
          Shop Women
        </button>
      </div>
    </div>
  );
}

function CategoryBoxCruiser() {
  const [isHover, setIsHover] = useState(false);

  return (
    <div
      className="category-box"
      onMouseEnter={() => setIsHover(true)}
      onMouseLeave={() => setIsHover(false)}
    >
      <img src="./images/homepage/category-cruisers.png" alt="" />
      <div className="button-box" style={{ bottom: isHover ? "250px" : "200px" }}>
        <button style={{ border: isHover ? "none" : "1px solid white", background:'none' }}>Cruiser</button>
        <button className="button-invisible" style={{ display: isHover ? "block" : "none" }}>
          Shop Men
        </button>
        <button className="button-invisible" style={{ display: isHover ? "block" : "none" }}>
          Shop Women
        </button>
      </div>
    </div>
  );
}

// Main component rendering all categories
export default function CategoryHomepage() {
  return (
    <div className="category-container">
      <CategoryBoxBestseller />
      <CategoryBoxMen />
      <CategoryBoxWomen />
      <CategoryBoxCruiser />
    </div>
  );
}
