// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect } from 'react';
import './GridHomepage.css';

const imageSets = {
  green: [
    '/images/homepage/Grid/green/Grid_01_green.jpeg', '/images/homepage/Grid/green/Grid_02_green.jpeg', '/images/homepage/Grid/green/Grid_03_green.jpeg',
    '/images/homepage/Grid/green/Grid_04_Green.jpeg', '/images/homepage/Grid/green/Grid_05_green.jpeg', '/images/homepage/Grid/green/Grid_06_green.jpeg'
  ],
  yellow: [
    '/images/homepage/Grid/yellow/Grid_01_yellow.jpeg', '/images/homepage/Grid/yellow/Grid_02_yellow.jpeg', '/images/homepage/Grid/yellow/Grid_03_yellow.jpeg',
    '/images/homepage/Grid/yellow/Grid_04_yellow.jpeg', '/images/homepage/Grid/yellow/Grid_05_yellow.jpeg', '/images/homepage/Grid/yellow/Grid_06_yellow.jpeg'
  ],
  grey: [
    '/images/homepage/Grid/grey/Grid_01_grey.jpeg', '/images/homepage/Grid/grey/Grid_02_grey.jpeg', '/images/homepage/Grid/grey/Grid_03_grey.jpeg',
    '/images/homepage/Grid/grey/Grid_04_grey.jpeg', '/images/homepage/Grid/grey/Grid_05_grey.jpeg', '/images/homepage/Grid/grey/Grid_06_grey.jpeg'
  ],
  blue: [
    '/images/homepage/Grid/blue/Grid_01_Blue.jpeg', '/images/homepage/Grid/blue/Grid_02_Blue.jpeg', '/images/homepage/Grid/blue/Grid_03_blue.jpeg',
    '/images/homepage/Grid/blue/Grid_04_Blue.jpeg', '/images/homepage/Grid/blue/Grid_05_blue.jpeg', '/images/homepage/Grid/blue/Grid_06_blue.jpeg'
  ]
};

const themes = ['green', 'yellow', 'grey', 'blue'];

const GridHomepage = () => {
  const [themeIndex, setThemeIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setThemeIndex((prev) => (prev + 1) % themes.length);
    }, 5000); // Change theme every 5 seconds

    return () => clearInterval(interval);
  }, []);

  const currentTheme = themes[themeIndex];
  const images = imageSets[currentTheme];

  return (
    <div className={`grid-container ${currentTheme}`}>
      {images.map((imgSrc, idx) => {
        // Overlay for main grid item
        if (idx === 0) {
          return (
            <div className="grid-item item-1" key={idx}>
              <img src={imgSrc} alt={`Grid ${currentTheme} ${idx + 1}`} />
              <div className="main-overlay">
                <div className="main-header">THE NEW WOOL CRUISER COLLECTION</div>
                <div className="main-title">Colors of Expression</div>
                <div className="main-btns">
                  <button className="shop-btn">SHOP MEN</button>
                  <button className="shop-btn">SHOP WOMEN</button>
                </div>
              </div>
            </div>
          );
        }
        // Overlay for top-right grid item
        if (idx === 1) {
          return (
            <div className="grid-item item-2" key={idx}>
              <img src={imgSrc} alt={`Grid ${currentTheme} ${idx + 1}`} />
              <div className="overlay overlay-topright">
                Allbirds partnered with Pantone to curate an exclusive palette of five colors that celebrate self-expression.
              </div>
            </div>
          );
        }
        // All other grid items: just the image
        return (
          <div className={`grid-item item-${idx + 1}`} key={idx}>
            <img src={imgSrc} alt={`Grid ${currentTheme} ${idx + 1}`} />
          </div>
        );
      })}
    </div>
  );
};

export default GridHomepage;
