// Code Generated by Sidekick is for learning and experimentation purposes only.
import axios from 'axios';
import React, { useState } from 'react';
import './Signup.css';
import { Link, useNavigate } from 'react-router-dom';


const usernameRegex = /^[a-zA-Z0-9]{3,20}$/;
const numberRegex = /^\d{10}$/;
// const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[A-Za-z\d]{8,}$/;

const SignUp = () => {
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [number, setNumber] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [data, setData] = useState(false);

  const navigate = useNavigate()

  const handleSubmit = async (e) => {
    e.preventDefault();

    // Validation

    if (!usernameRegex.test(username)) {
      alert("Username must be 3-20 letters/numbers, no spaces.");
      return;
    }
    if (!numberRegex.test(number)) {
      alert("Contact number must be a valid 10 digit number.");
      return;
    }
    // if (!passwordRegex.test(password)) {
    //   alert("Password must be at least 8 chars, 1 uppercase, 1 lowercase, 1 number.");
    //   return;
    // }
    if (password !== confirmPassword) {
      alert("Passwords do not match.");
      return;
    }

    try {
      const res = await axios.get("http://localhost:3000/user");
      const users = res.data;
      const currentUser = users.find((item) => item.username === username);

      if (currentUser) {
        alert("User Already Exists");
        return;
      }

      await axios.post("http://localhost:3000/user", { email, username, password, number });
      alert("Successful Signup");
      setUsername("");
      setPassword("");
      setConfirmPassword("");
      setNumber("");

      setData(true);
    } catch (error) {
      console.log(error);
      alert("There was a problem signing up. Try again later.");
    }
  };

  if (data) {
    navigate("/");
  }

  return (
    <div className='form-container'>
      <form className='form' onSubmit={handleSubmit}>
        <h3>Sign Up</h3>
        <div className="username">
          <label htmlFor="email">Enter Email</label>
          <input type="email" id='email' value={email} placeholder='Email' onChange={(e) => { setEmail(e.target.value) }} />
        </div>
        <div className="username">
          <label htmlFor="name">Enter Name</label>
          <input type="text" id='name' value={username} placeholder='Name' onChange={(e) => { setUsername(e.target.value) }} />
        </div>
        <div className="phone">
          <label htmlFor="number">Enter Contact Number</label>
          <input type="text" id='number' value={number} placeholder='Contact Number' onChange={(e) => { setNumber(e.target.value) }} />
        </div>
        <div className="password">
          <label htmlFor="password">Enter Password</label>
          <input type="password" id='password' value={password} placeholder='Password' onChange={(e) => { setPassword(e.target.value) }} />
        </div>
        <div className="password">
          <label htmlFor="Cpassword">Confirm Password</label>
          <input type="password" id='Cpassword' value={confirmPassword} placeholder='Confirm Password' onChange={(e) => { setConfirmPassword(e.target.value) }} />
        </div>
        <button type="submit">Submit</button>
        <p>Already have an account? <Link to='/login'><span>Click Here</span></Link></p>
      </form>
    </div>
  );
};

export default SignUp;
