// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from "react";
import "./CartDrawer.css";
import { FaTimes } from "react-icons/fa";
import { useCart } from "./CartContext.jsx";
import { useNavigate } from "react-router-dom";

const CartDrawer = () => {
  const { cartOpen, closeCart, cartItems, increaseQty, decreaseQty, removeFromCart } = useCart();
  const navigate = useNavigate();

  const handleCheckout = () => {
    closeCart();
    navigate('/checkout');
  };

  return (
    <>
      {/* Backdrop overlay */}
      <div
        className={`cart-backdrop ${cartOpen ? "visible" : ""}`}
        onClick={closeCart}
        aria-hidden={!cartOpen}
      />

      <div className={`cart-drawer ${cartOpen ? "open" : ""}`}>
        <div className="cart-header">
          <div className="cart-header-left">
            <span className="cart-title">CART ({cartItems.length})</span>
            <span className="cart-promo">Spend $30 more to save $30!</span>
          </div>
          <button className="cart-close-btn" onClick={closeCart} aria-label="Close cart">
            <FaTimes size={22} />
          </button>
        </div>
      <div className="cart-body">
        {cartItems.length === 0 ? (
          <div className="cart-empty">Your cart is empty.</div>
        ) : (
          cartItems.map((item) => (
            <div className="cart-item" key={item.id}>
              <img src={item.image} alt={item.name} />
              <div className="cart-item-details">
                <div className="cart-item-name">{item.name}</div>
                <div className="cart-item-info">
                  <span>Color: {item.color}</span>
                  <span>Size: {item.size}</span>
                </div>
                <div className="cart-item-actions">
                  <button onClick={() => decreaseQty(item.id)} aria-label={`Decrease quantity of ${item.name}`}>-</button>
                  <span>{item.quantity}</span>
                  <button onClick={() => increaseQty(item.id)} aria-label={`Increase quantity of ${item.name}`}>+</button>
                </div>
              </div>
              <div className="cart-item-right">
                <div className="cart-item-price">${item.price}</div>
                <button className="cart-remove-btn" onClick={() => removeFromCart(item.id)} aria-label={`Remove ${item.name}`}><FaTimes /></button>
              </div>
            </div>
          ))
        )}
      </div>
      <div className="cart-footer">
        <div className="cart-subtotal">
          <span>Subtotal</span>
          <span>
            ${cartItems.reduce((sum, item) => sum + item.price * item.quantity, 0)}
          </span>
        </div>
  <button className="cart-checkout-btn" onClick={handleCheckout}>CHECKOUT</button>
        <div className="cart-express-btns">
          <button className="amazon-pay">amazon pay</button>
          <button className="paypal">PayPal</button>
          <button className="shop-pay">shop Pay</button>
        </div>
      </div>
      </div>
    </>
  );
};

export default CartDrawer;
