// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState } from "react";
import "./chat.css";
import { useCart } from "./CartContext.jsx";

const chatQuestions = [
  "How do I make a return or exchange?",
  "How do Allbirds fit?",
  "How do you ship?",
  "When will you restock?"
];

function Chat() {
  const [isOpen, setIsOpen] = useState(false);
  const { cartOpen } = useCart();

  return (
    <>
      {/* Chat Button */}
      <button
        className={`chat-button ${cartOpen ? 'cart-open' : ''}`}
        onClick={() => setIsOpen(true)}
        aria-expanded={isOpen}
      >
        Chat
      </button>

      {/* Chat Window */}
      {isOpen && (
        <div className={`chat-popup ${cartOpen ? 'cart-open' : ''}`}>
          <div className="chat-header">
            <span>Hi, how can we help you?</span>
            <button className="chat-close" onClick={() => setIsOpen(false)}>×</button>
          </div>
          <input
            className="chat-search"
            placeholder="Maybe your answer's in here..."
          />
          <div className="chat-questions">
            {chatQuestions.map((q, idx) => (
              <button key={idx} className="chat-question">
                {q}
              </button>
            ))}
          </div>
          <div className="chat-footer">
            <span>
              Apologies, we're out right now!
            </span>
          </div>
        </div>
      )}
    </>
  );
}

export default Chat;
