// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from "react";
import "./collection.css";

function Collection() {
  return (
    <div className="collection-container">

      {/* Card 1 */}
      <div className="collection-card">
        <div
          className="collection-bg"
          style={{
            backgroundImage:
              "url(public/images/homepage/25Q3_August_Remix_Site_3xPromo-01_Desktop-Mobile_9x16_19c117cd-e71f-4d92-bacc-4d351a1194db.jpg.jpeg)",
          }}
        />
        <div className="collection-center">
          <h2 className="collection-title">The New Remix Collection</h2>
          <p className="collection-subtitle">
            Sustainably crafted with superior comfort and effortless style.
          </p>
        </div>
        <div className="collection-buttons" style={{width:"300px"}}>
          <a className="collection-btn" href="#" >
            LEARN MORE
          </a>
        </div>
      </div>

      {/* Card 2 */}
      <div className="collection-card">
        <div
          className="collection-bg"
          style={{
            backgroundImage:
              "url(public/images/homepage/25Q2_BAU_Site_Homepage_3xPromo-TreeCollection_Lifestyle_Desktop_2x3_9bfe6ee7-e251-4075-a78c-a0e617dd8e87.jpg.jpeg)",
          }}
        />
        <div className="collection-center">
          <h2 className="collection-title">Tree Collection</h2>
          <p className="collection-subtitle">
            Comfort, breathability, and style for miles (and miles and miles).
          </p>
        </div>
        <div className="collection-buttons">
          <a className="collection-btn" href="#">
            SHOP MEN
          </a>
          <a className="collection-btn" href="#">
            SHOP WOMEN
          </a>
        </div>
      </div>

      {/* Card 3 */}
      <div className="collection-card">
        <div
          className="collection-bg"
          style={{
            backgroundImage:
              "url(public/images/homepage/25Q2_BAU_Site_Homepage_3xPromo-BreezyBestSellers_Lifestyle_Desktop_2x3_e4f79209-6ff4-4ce1-bf1d-675dbe340da2.png)",
          }}
        />
        <div className="collection-center">
          <h2 className="collection-title">Breezy Bestsellers</h2>
          <p className="collection-subtitle">
            Light and airy staples for anytime, anywhere.
          </p>
        </div>
        <div className="collection-buttons">
          <a className="collection-btn" href="#">
            SHOP MEN
          </a>
          <a className="collection-btn" href="#">
            SHOP WOMEN
          </a>
        </div>
      </div>

    </div>
  );
}

export default Collection;
