// Code Generated by Sidekick is for learning and experimentation purposes only.
import React, { useState, useEffect } from 'react';
import './GridHomepage.css';

const imageSets = {
  green: [
    'public/images/homepage/Grid/green/Grid_01_green.jpeg', 'public/images/homepage/Grid/green/Grid_02_green.jpeg', 'public/images/homepage/Grid/green/Grid_03_green.jpeg',
    'public/images/homepage/Grid/green/Grid_04_green.jpeg', 'public/images/homepage/Grid/green/Grid_05_green.jpeg', 'public/images/homepage/Grid/green/Grid_06_green.jpeg'
  ],
  yellow: [
    'public/images/homepage/Grid/yellow/Grid_01_yellow.jpeg', 'public/images/homepage/Grid/yellow/Grid_02_yellow.jpeg', 'public/images/homepage/Grid/yellow/Grid_03_yellow.jpeg',
    'public/images/homepage/Grid/yellow/Grid_04_yellow.jpeg', 'public/images/homepage/Grid/yellow/Grid_05_yellow.jpeg', 'public/images/homepage/Grid/yellow/Grid_06_yellow.jpeg'
  ],
  grey: [
    'public/images/homepage/Grid/grey/Grid_01_grey.jpeg', 'public/images/homepage/Grid/grey/Grid_02_grey.jpeg', 'public/images/homepage/Grid/grey/Grid_03_grey.jpeg',
    'public/images/homepage/Grid/grey/Grid_04_grey.jpeg', 'public/images/homepage/Grid/grey/Grid_05_grey.jpeg', 'public/images/homepage/Grid/grey/Grid_06_grey.jpeg'
  ],
  blue: [
    'public/images/homepage/Grid/blue/Grid_01_Blue.jpeg', 'public/images/homepage/Grid/blue/Grid_02_Blue.jpeg', 'public/images/homepage/Grid/blue/Grid_03_Blue.jpeg',
    'public/images/homepage/Grid/blue/Grid_04_Blue.jpeg', 'public/images/homepage/Grid/blue/Grid_05_Blue.jpeg', 'public/images/homepage/Grid/blue/Grid_06_Blue.jpeg'
  ]
};

const themes = ['green', 'yellow', 'grey', 'blue'];

const GridHomepage = () => {
  const [themeIndex, setThemeIndex] = useState(0);

//   useEffect(() => {
//     const interval = setInterval(() => {
//       setThemeIndex((prev) => (prev + 1) % themes.length);
//     }, 5000); // Change theme every 5 seconds

//     return () => clearInterval(interval);
//   }, []);

  const currentTheme = themes[themeIndex];
  const images = imageSets[currentTheme];

  return (
    <div className={`grid-container ${currentTheme}`}>
      {images.map((imgSrc, idx) => (
        <div className={`grid-item item-${idx + 1}`} key={idx}>
          <img src={imgSrc} alt={`Grid ${currentTheme} ${idx + 1}`} />
        </div>
      ))}
    </div>
  );
};

export default GridHomepage;
