// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useState } from 'react';
import './ProductCard.css';

const ProductCard = ({ product }) => {
  // Track which color is selected
  const [selectedColorIdx, setSelectedColorIdx] = useState(0);

  // Get the selected color object
  const selectedColor = product.colors[selectedColorIdx];

  return (
    <div className="product-card">
      <div className="product-card__badge">NEW</div>
      <img
        src={selectedColor.img}
        alt={product.Title}
        className="product-card__image"
      />
      <div className="product-card__details">
        <h2 className="product-card__title">{product.Title}</h2>
        <p className="product-card__category">{product.Cat}</p>
        <p className="product-card__price">{product.Price}</p>
        <div className="product-card__colors">
          {product.colors.map((color, idx) => (
            <span
              key={color.code}
              className={`product-card__color${idx === selectedColorIdx ? ' selected' : ''}`}
              style={{ backgroundColor: color.code, cursor: 'pointer' }}
              onClick={() => setSelectedColorIdx(idx)}
            ></span>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ProductCard;
