// Code Generated by Sidekick is for learning and experimentation purposes only.

import React, { useState } from "react";
import womenProducts from "./womenProducts";
import "./Women.css";
import ProductCard from "../../components/SectionComponent/productcard"; // <-- adjust path as needed


function Women() {
  const [hoveredCardId, setHoveredCardId] = useState(null);
  const [selectedVariants, setSelectedVariants] = useState(
    womenProducts.reduce((acc, p) => { acc[p.id] = 0; return acc; }, {})
  );
  const [sortOption, setSortOption] = useState("FEATURED");
  const [showFilterPanel, setShowFilterPanel] = useState(false);
  const [labelFilter, setLabelFilter] = useState([]);
  const [colorFilter, setColorFilter] = useState([]);
  const [maxPriceFilter, setMaxPriceFilter] = useState(500);

  // Get all unique color names
  const allColors = [
    ...new Set(womenProducts.flatMap(p => p.variants.map(v => v.colorName))),
  ];

  const handleColorSelect = (productId, variantIdx) => {
    setSelectedVariants({ ...selectedVariants, [productId]: variantIdx });
  };

  const filteredProducts = womenProducts.filter(product => {
    const labelMatch =
      labelFilter.length === 0 || labelFilter.includes(product.label);
    const colorMatch =
      colorFilter.length === 0 ||
      product.variants.some(v => colorFilter.includes(v.colorName));
    const priceMatch = product.price <= maxPriceFilter;
    return labelMatch && colorMatch && priceMatch;
  });

  const sortedProducts = [...filteredProducts].sort((a, b) => {
    switch (sortOption) {
      case "PRICE_LOW_HIGH": return a.price - b.price;
      case "PRICE_HIGH_LOW": return b.price - a.price;
      case "ALPHA_AZ": return a.name.localeCompare(b.name);
      case "ALPHA_ZA": return b.name.localeCompare(a.name);
      case "DATE_NEW_OLD": return b.id - a.id;
      case "DATE_OLD_NEW": return a.id - b.id;
      default: return 0;
    }
  });

  return (
    <div className="women-section-bg">
      <div className="women-breadcrumb">
        Home <span>/</span> Women's Shoes
      </div>
      <h1 className="women-title">Women's Shoes</h1>
      <p className="women-desc">
        The world's most comfortable shoes for life’s everyday adventures.
      </p>

      {/* Controls */}
      <div className="women-controls">
        <div className="women-filter" onClick={() => setShowFilterPanel(s => !s)}>
          <div className="filter-icon-circle"><svg
              className="filter-sliders-svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
              fill="none"
            >
              <circle
                cx="16"
                cy="16"
                r="15"
                stroke="#23201c"
                strokeWidth="1"
                fill="none"
              />
              <line x1="10" y1="12" x2="22" y2="12" stroke="#23201c" strokeWidth="1" />
              <circle cx="13" cy="12" r="1.2" fill="#23201c" />
              <line x1="10" y1="16" x2="22" y2="16" stroke="#23201c" strokeWidth="1" />
              <circle cx="19" cy="16" r="1.2" fill="#23201c" />
              <line x1="10" y1="20" x2="22" y2="20" stroke="#23201c" strokeWidth="1" />
              <circle cx="16" cy="20" r="1.2" fill="#23201c" />
            </svg></div>
          FILTER{" "}
          <span className="women-product-count">
            ({filteredProducts.length} products)
          </span>
        </div>
        <select
          className="featured-dropdown"
          value={sortOption}
          onChange={e => setSortOption(e.target.value)}
        >
          <option value="FEATURED">FEATURED</option>
          <option value="BESTSELLING">BEST SELLING</option>
          <option value="ALPHA_AZ">ALPHABETICALLY, A-Z</option>
          <option value="ALPHA_ZA">ALPHABETICALLY, Z-A</option>
          <option value="PRICE_LOW_HIGH">PRICE, LOW TO HIGH</option>
          <option value="PRICE_HIGH_LOW">PRICE, HIGH TO LOW</option>
          <option value="DATE_OLD_NEW">DATE, OLD TO NEW</option>
          <option value="DATE_NEW_OLD">DATE, NEW TO OLD</option>
        </select>
      </div>

      {/* Pills bar */}
      <div className="filter-pills-bar">
        {labelFilter.map(lbl => (
          <span key={lbl} className="filter-pill">
            {lbl}
            <button className="filter-pill-remove" onClick={() => setLabelFilter(labelFilter.filter(l => l !== lbl))} aria-label={`Remove ${lbl} filter`}>×</button>
          </span>
        ))}
        {colorFilter.map(color => (
          <span key={color} className="filter-pill">
            {color}
            <button className="filter-pill-remove" onClick={() => setColorFilter(colorFilter.filter(c => c !== color))} aria-label={`Remove ${color} filter`}>×</button>
          </span>
        ))}
        {maxPriceFilter < 500 && (
          <span className="filter-pill">
            {`≤ $${maxPriceFilter}`}
            <button className="filter-pill-remove" onClick={() => setMaxPriceFilter(500)} aria-label="Remove price filter">×</button>
          </span>
        )}
        {(labelFilter.length > 0 || colorFilter.length > 0 || maxPriceFilter < 500) && (
          <button
            className="filter-pill-clearall"
            onClick={() => {
              setLabelFilter([]);
              setColorFilter([]);
              setMaxPriceFilter(500);
            }}
          >
            Clear All
          </button>
        )}
      </div>

      {/* Filter Panel */}
      {showFilterPanel && (
        <div className="filter-panel">
          <div className="filter-group">
            <h4>Label:</h4>
            {["New", "Bestseller"].map(lbl => (
              <label key={lbl}>
                <input
                  type="checkbox"
                  checked={labelFilter.includes(lbl)}
                  onChange={e => e.target.checked
                    ? setLabelFilter([...labelFilter, lbl])
                    : setLabelFilter(labelFilter.filter(l => l !== lbl))
                  }
                /> {lbl}
              </label>
            ))}
          </div>
          <div className="filter-group">
            <h4>Color:</h4>
            {allColors.map(c => (
              <label key={c}>
                <input
                  type="checkbox"
                  checked={colorFilter.includes(c)}
                  onChange={e => e.target.checked
                    ? setColorFilter([...colorFilter, c])
                    : setColorFilter(colorFilter.filter(cl => cl !== c))
                  }
                /> {c}
              </label>
            ))}
          </div>
          <div className="filter-group">
            <label>
              <h4>Price: ${maxPriceFilter}</h4>
            </label>
            <input
              type="range"
              min="0"
              max="500"
              value={maxPriceFilter}
              onChange={e => setMaxPriceFilter(Number(e.target.value))}
            />
          </div>
          <button onClick={() => setShowFilterPanel(false)}>
            Apply Filters
          </button>
        </div>
      )}

      {/* Products Grid */}
      <div className="women-products-wrapper">
        {sortedProducts.map(product => {
          const currentVariant = product.variants[selectedVariants[product.id]];
          const hasSizes = product.sizes && product.sizes.length > 0;
          return (
            <ProductCard
              key={product.id}
              product={product}
              currentVariant={currentVariant}
              selectedVariantIdx={selectedVariants[product.id]}
              hasSizes={hasSizes}
              hovered={hoveredCardId === product.id}
              onMouseEnter={() => setHoveredCardId(product.id)}
              onMouseLeave={() => setHoveredCardId(null)}
              handleColorSelect={handleColorSelect}
              gender="womens"
            />
          );
        })}
      </div>
    </div>
  );
}

export default Women;
