// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import './checkout.css';

export default function Checkout() {
  return (
    <div className="checkout-page">
      <div className="checkout-main">
        <img
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Allbirds_logo.svg/2560px-Allbirds_logo.svg.png"
          alt="allbirds"
          className="logo"
        />
        <div className="express-checkout">
          <div className="express-title">Express checkout</div>
          <div className="express-buttons">
            <button className="shop-btn">shop</button>
            <button className="paypal-btn">PayPal</button>
          </div>
          <div className="divider">
            <span>OR</span>
          </div>
        </div>

        <div className="checkout-section">
          <h2>Contact</h2>
          <div className="input-row">
            <input type="email" placeholder="Email" />
            <a href="/" className="signin-link">Sign in</a>
          </div>
          <div className="checkbox-row">
            <input type="checkbox" id="news1" checked readOnly />
            <label htmlFor="news1">Email me with news and offers</label>
          </div>
        </div>

        <div className="checkout-section">
          <h2>Delivery</h2>
          <select>
            <option>United States</option>
          </select>
          <div className="input-row">
            <input type="text" placeholder="First name" />
            <input type="text" placeholder="Last name" />
          </div>
          <input type="text" placeholder="Company (optional)" />
          <input type="text" placeholder="Address" />
          <input type="text" placeholder="Apartment, suite, etc. (optional)" />
          <div className="input-row">
            <input type="text" placeholder="City" />
            <input type="text" placeholder="State" />
            <input type="text" placeholder="ZIP code" />
          </div>
          <div className="checkbox-row">
            <input type="checkbox" id="news2" />
            <label htmlFor="news2">Text me with news and offers</label>
          </div>
        </div>

        <div className="checkout-section">
          <h2>Shipping method</h2>
          <div className="shipping-box">
            Enter your shipping address to view available shipping methods.
          </div>
        </div>

        <div className="checkout-section">
          <h2>Payment</h2>
          <div className="subtitle">
            All transactions are secure and encrypted.
          </div>
          <div className="payment-methods">
            <label>
              <input type="radio" name="payment" checked readOnly />
              Credit card
            </label>
            <span className="card-icons">
              <img src="https://img.icons8.com/color/48/000000/visa.png" alt="Visa" />
              <img src="https://img.icons8.com/color/48/000000/mastercard-logo.png" alt="MC" />
              <img src="https://img.icons8.com/color/48/000000/amex.png" alt="Amex" />
              <span className="card-plus">+5</span>
            </span>
          </div>
          <div className="input-row">
            <input type="text" placeholder="Card number" />
          </div>
          <div className="input-row">
            <input type="text" placeholder="Expiration date (MM / YY)" />
            <input type="text" placeholder="Security code" />
          </div>
          <input type="text" placeholder="Name on card" />

          <div className="payment-methods">
            <label>
              <input type="radio" name="payment" />
              PayPal
            </label>
            <span className="paypal-label">PayPal</span>
          </div>
          <div className="payment-methods">
            <label>
              <input type="radio" name="payment" />
              Afterpay
            </label>
          </div>
        </div>

        <div className="checkout-section">
          <h2>Remember me</h2>
          <div className="checkbox-row">
            <input type="checkbox" id="remember" checked readOnly />
            <label htmlFor="remember">Save my information for a faster checkout with a Shop account</label>
          </div>
          <div className="input-row">
            <input type="text" value="+1" readOnly />
          </div>
          <div className="secure-label">Secure and encrypted</div>
          <button className="paynow-btn">Pay now</button>
          <div className="terms">
            Your info will be saved to a Shop account. By continuing, you agree to Shop’s Terms of Service and acknowledge the Privacy Policy.
          </div>
          <div className="policies">
            <a href="/">Refund policy</a>
            <a href="/">Privacy policy</a>
            <a href="/">Terms of service</a>
          </div>
          <div className="terms-link">
            By placing this order, you agree to our Terms of Service and understand our Privacy Policy.
          </div>
        </div>
      </div>
      <div className="checkout-sidebar">
        <div className="sidebar-cart">
          <div className="cart-item">
            <img className="cart-img" src="https://allbirds.com/cdn/shop/products/Womens_Wool_Crusher_Burgundy_White.png" alt="" />
            <div>
              <div><b>2</b> Women's Wool Cruiser - Burgundy<br/>(Natural White Sole)</div>
              <div className="cart-old">$200.00</div>
              <div className="cart-new">$180.32</div>
              <div className="cart-promo">SPENDANDSAVE30 ($-19.68)</div>
            </div>
          </div>
          <div className="cart-item">
            <img className="cart-img" src="https://allbirds.com/cdn/shop/products/Womens_Cruiser_Slip_On_Corduroy_Dark_Tan.png" alt="" />
            <div>
              <div><b>1</b> Women's Cruiser Slip On Corduroy - Dark Tan<br/> (Stony Cream Sole)</div>
              <div className="cart-old">$105.00</div>
              <div className="cart-new">$94.68</div>
              <div className="cart-promo">SPENDANDSAVE30 ($-10.32)</div>
            </div>
          </div>
        </div>
        <hr/>
        <div className="sidebar-suggest">
          <h2>You might also like</h2>
          <div className="suggest-item">
            <img src="https://allbirds.com/cdn/shop/products/Belt_Bag_True_Black.png" alt="" className="suggest-img"/>
            <div>
              <b>Recycled Belt Bag - True Black</b><br/>
              One Size<br/>
              <span className="price">$35.00</span>
            </div>
            <button className="add-btn">Add</button>
          </div>
          <div className="suggest-item">
            <img src="https://allbirds.com/cdn/shop/products/Shoe_Bag_True_Black.png" alt="" className="suggest-img"/>
            <div>
              <b>Recycled Shoe Bag - True Black</b><br/>
              One Size<br/>
              <span className="price">$20.00</span>
            </div>
            <button className="add-btn">Add</button>
          </div>
          <div className="suggest-item">
            <img src="https://allbirds.com/cdn/shop/products/Belt_Bag_Teal_Blue.png" alt="" className="suggest-img"/>
            <div>
              <b>Recycled Belt Bag - Twilight Teal</b><br/>
              One Size<br/>
              <span className="price">$35.00</span>
            </div>
            <button className="add-btn">Add</button>
          </div>
        </div>
        <div className="sidebar-discount">
          <input type="text" placeholder="Discount code or gift card"/>
          <button className="apply-btn" disabled>Apply</button>
        </div>
        <div className="sidebar-totals">
          <div>Subtotal · 3 items <span>$275.00</span></div>
          <div>Shipping <span>Enter shipping address</span></div>
          <hr/>
          <div className="total-row">
            <b>Total</b> <span className="total-price">USD $275.00</span>
          </div>
          <div className="total-savings">
            <span>💳 TOTAL SAVINGS $30.00</span>
          </div>
        </div>
      </div>
    </div>
  );
}
