// Code Generated by Sidekick is for learning and experimentation purposes only.
// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import { menProducts } from "./menProducts";
import './Men.css'; // Make sure this path is correct in your project

function Men() {
  return (
    <div className="men-section-bg">
      <nav className="men-breadcrumb">
        Home <span>/</span> Men&apos;s Shoes
      </nav>

      <h1 className="men-title">Men&apos;s Shoes</h1>
      <p className="men-desc">
        The world's most comfortable shoes for life’s everyday adventures.
      </p>

      <div className="men-controls">
        <div className="men-filter">
          <span className="men-filter-icon">&#9776;</span> {/* Hamburger icon */}
          FILTER <span className="men-product-count">(41 products)</span>
        </div>
        <button className="men-featured-btn">
          FEATURED <span className="men-featured-arrow">&#x25BC;</span>
        </button>
      </div>

      <div className="men-product-grid">
        {menProducts.map(product => (
          <div key={product.id} className="men-card">
            {product.tag && <div className="men-card-tag">{product.tag}</div>}
            <img 
              src={product.image} 
              alt={product.name} 
              className="men-card-image"
            />
            <h3 className="men-card-title">{product.name}</h3>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Men;
