// Code Generated by Sidekick is for learning and experimentation purposes only.
export const womenProducts = [
  {
    id: 1,
    name: "WOMEN'S TREE DASHER 2",
    image: "https://example.com/green-shoe.jpg", // Use your image URLs
    tag: "BESTSELLER"
  },
  {
    id: 2,
    name: "WOMEN'S TREE RUNNER NZ",
    image: "https://example.com/navy-shoe.jpg",
    tag: "NEW"
  },
  {
    id: 3,
    name: "WOMEN'S WOOL CRUISER",
    image: "https://example.com/red-shoe.jpg",
    tag: "NEW"
  },
  {
    id: 4,
    name: "WOMEN'S WOOL CRUISER SLIP ON",
    image: "https://example.com/grey-shoe.jpg",
    tag: "NEW"
  }
];
