// Code Generated by Sidekick is for learning and experimentation purposes only.
// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from "react";
import { womenProducts } from "./womenProducts";
import './Women.css'; // Make sure this path is correct in your project

function Women() {
  return (
    <div className="women-section-bg">
      <nav className="women-breadcrumb">
        Home <span>/</span> Women&apos;s Shoes
      </nav>

      <h1 className="women-title">Women&apos;s Shoes</h1>
      <p className="women-desc">
        The world's most comfortable shoes for life’s everyday adventures.
      </p>

      <div className="women-controls">
        <div className="women-filter">
          <span className="women-filter-icon">&#9776;</span> {/* Hamburger icon */}
          FILTER <span className="women-product-count">(41 products)</span>
        </div>
        <button className="women-featured-btn">
          FEATURED <span className="women-featured-arrow">&#x25BC;</span>
        </button>
      </div>

      <div className="women-product-grid">
        {womenProducts.map(product => (
          <div key={product.id} className="women-card">
            {product.tag && <div className="women-card-tag">{product.tag}</div>}
            <img 
              src={product.image} 
              alt={product.name} 
              className="women-card-image"
            />
            <h3 className="women-card-title">{product.name}</h3>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Women;
