// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import Navbar from './sections/Navbar';
import Homepage from './sections/Homepage';
import Header from './components/Header';
import Footer from './components/footer';
import Homeproduct from './Homeproduct';
import ProductCard from './components/ProductCard';
import './App.css';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import Men from './sections/Men';
function App() {
  return (
    <Router>
      <Header />
      <Navbar />
      
      <Routes>
        {/* Homepage route */}
        <Route 
          path="/" 
          element={
            <>
              <Homepage />
              <div className="App">
                {Homeproduct.map(product => (
                  <ProductCard key={product.id} product={product} />
                ))}
              </div>
              <Footer />
            </>
          } 
        />

        {/* Men section route */}
        <Route 
          path="/Men" 
          element={
            <>
              <Men />
              <Footer />
            </>
          } 
        />

      </Routes>
    </Router>
  );
}

export default App;
