// Code Generated by Sidekick is for learning and experimentation purposes only.
import React from 'react';
import Homeproduct from './Homeproduct';
import ProductCard from './components/ProductCard';
import './App.css';

function App() {
  return (
    <div className="App">
      {Homeproduct.map(product => (
        <ProductCard key={product.id} product={product} />
      ))}
    </div>
  );
}

export default App;
