// Code Generated by Sidekick is for learning and experimentation purposes only.
const Homeproduct = [
  {
    id: 1,
    Title: "MEN'S RUNNER NZ CORDUROY",
    Cat: 'Dark Tan',
    Price: '$20',
    img: "/images/Products/A11946_25Q3_Runner-NZ-Corduroy-Dark-Tan-Stony-Cream-Sole_PDP_LEFT__1.png",
    colors: [
      { code: '#8f5226ff', img: "/images/Products/A11946_25Q3_Runner-NZ-Corduroy-Dark-Tan-Stony-Cream-Sole_PDP_LEFT__1.png" },
      { code: '#0404729e', img: "/images/Products/A11893_25Q3_Tree-Glider-Thunder-Green-Stony-Cream-Sole_PDP_LEFT__1.png" },
      { code: '#F5F5DC', img: "/images/Products/A11946_25Q3_Runner-NZ-Corduroy-Dark-Tan-Stony-Cream-Sole_PDP_LEFT__1.png" }
    ]
  },
  // ...add other products
  
];

export default Homeproduct;
