// Code Generated by Sidekick is for learning and experimentation purposes only.

import React from "react";
import { Link } from "react-router-dom";
import "./productcard.css";

function ProductCard({
  product,
  currentVariant,
  selectedVariantIdx,
  hasSizes,
  hovered,
  onMouseEnter,
  onMouseLeave,
  handleColorSelect,
  gender
}) {
  return (
    <div
      className={`product-card${hovered ? " hover" : ""}`}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      style={{ position: "relative", overflow: "visible" }}
    >
      <Link to={`/singleProduct/${gender}/${product.id}`}>
        {product.label && <span className="product-label">{product.label}</span>}
        <img
          src={currentVariant.image}
          alt={`${product.product_name || product.name} - ${currentVariant.colorName}`}
          className="product-image"
          draggable="false"
        />
      </Link>
      <div className="product-body">
        <h3 className="product-title">
          {product.product_name ? product.product_name : product.name}
        </h3>
        {product.subtitle && (
          <div className="product-subtitle">{product.subtitle}</div>
        )}
        {/* Only render color variant subtitle if it exists */}
        {currentVariant.subtitle && (
          <div className="product-subtitle">{currentVariant.subtitle}</div>
        )}
        <div className="product-price">${product.price}</div>
        <div className="product-colors" onClick={e => e.stopPropagation()}>
          {(product.variants || []).map((variant, idx) => (
            <span
              key={idx}
              className={`color-dot${selectedVariantIdx === idx ? " selected" : ""}`}
              style={{ background: variant.colorHex }}
              title={variant.colorName}
              onClick={() => handleColorSelect(product.id, idx)}
            />
          ))}
          {!!product.extraColors && product.extraColors > 0 && (
            <span className="extra-colors">{`+${product.extraColors}`}</span>
          )}
        </div>
      </div>
      {hovered && hasSizes && (
        <div className="size-dropdown-float">
          {(product.sizes || []).map(size => (
            <div className="size-box-float" key={size}>
              {size}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default ProductCard;
